In [ ]:
import numpy as np

In [ ]:
array = np.array([1,2,3,4,5,6])  # 1d  # shape [6]
array, print(type(array)),array.shape,array.ndim

# converting an array into list.

In [ ]:
array,type(array)

In [ ]:
list1 = array.tolist() # converting an array into list.
list1, type(list1)

In [ ]:
list1 = [24,78,45,4]
array = np.array(list1)
array,type(array)

## creating an empty array

In [ ]:
array =np.array([])
array

## Functions

## 1. zeros()

It will create an array where all the elements will be zero

In [ ]:
arr = np.zeros(4,dtype=int)
arr,arr.dtype,type(arr)

In [ ]:
array = np.zeros(3)
array,array.dtype,type(array)

In [ ]:
array = np.zeros(2, dtype = 'str')
array                                         #in string data type it is not give a zeros 

In [ ]:
array = np.zeros(2, dtype = 'int')
array

In [ ]:
arr = np.zeros((2,2), dtype = 'int')
arr

In [ ]:
arr = np.zeros([2,2], dtype = 'int')
arr

In [ ]:
arra =np.zeros((2,6),dtype = "int")
arra

In [ ]:
arr = np.zeros([5,5],dtype = int)
arr

In [ ]:
arr = np.zeros([5,5])
arr

## 2. ones()

In [ ]:
### It will create an array where all the elements will be one.

In [ ]:
array = np.ones(5)
array,array.dtype

In [ ]:
arr = np.ones((5,5), dtype='int')
arr

In [ ]:
arr = np.ones((2,2),dtype = "str")
arr

In [ ]:
arr1 = np.ones((3,4))
arr1

In [ ]:
arr1 = np.ones([3,4],dtype = int)
arr1

## 3. arange()

In [ ]:
# range (0,10) == 0,1,2,3....9
# range(2,10,2) == 2,4,6,8
# arange(satrt_index,end_index,step_size)

In [ ]:
arr = np.arange(1,10) #(1,2,3,....9)(n,n-1)
arr

In [ ]:
arr = np.arange(1,10,2)  # 1,3,5,
arr

In [ ]:
arr = np.arange(1,10).reshape(3,3)    # 9 (9*1,1*9,3*3)
arr

In [ ]:
arr = np.arange(1,10).reshape(1,9)    # 9 (9*1,1*9)
arr

## 4. linspace()

In [ ]:
linspace(start, end, num = digit, retstep= True)

In [ ]:
array = np.linspace(0,50) # by default it give us 50 nums
array 
print(len(array)) 


In [ ]:
array = np.linspace(1,20)  # start number and end number == 50 by default 
array

In [ ]:
array = np.linspace(1,10)
array

In [ ]:
1.36734694- 1.18367347

In [ ]:
 9.63265306-9.44897959

In [2]:
import numpy as np

In [5]:
arr = np.linspace(0,20,num = 21,retstep=True) 
arr



(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20.]),
 1.0)

In [6]:
array = np.linspace(2,30, num=20, retstep=True) 
array

(array([ 2.        ,  3.47368421,  4.94736842,  6.42105263,  7.89473684,
         9.36842105, 10.84210526, 12.31578947, 13.78947368, 15.26315789,
        16.73684211, 18.21052632, 19.68421053, 21.15789474, 22.63157895,
        24.10526316, 25.57894737, 27.05263158, 28.52631579, 30.        ]),
 1.4736842105263157)

In [7]:
array = np.linspace(0,10,num = 6,retstep=True)
array

(array([ 0.,  2.,  4.,  6.,  8., 10.]), 2.0)

In [10]:
array = np.linspace(0,20, retstep=True) # by default it give us 50 nums
array,type(array)

((array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
          2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
          4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
          6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
          8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
         10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
         12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
         14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
         16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
         18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ]),
  0.40816326530612246),
 tuple)

## 5. eye()   
we can take +ve and  -ve value of k 

In [11]:
import numpy as np

In [12]:
arr = np.eye(2,2, dtype= 'int')
arr

array([[1, 0],
       [0, 1]])

In [13]:
arr = np.eye(5, dtype= 'int')
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
arr = np.eye(3,5, dtype= 'int')
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [15]:
arr = np.eye(3,5, dtype= 'int', k= 1)
arr

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [16]:
arr = np.eye(3,5, dtype= 'int', k= 2)
arr

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
arr = np.eye(2,3,dtype = 'int',k = 1)
arr

array([[0, 1, 0],
       [0, 0, 1]])

In [19]:
arr = np.eye(3,5, dtype= 'int', k= 3)
arr

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [26]:
arr = np.eye(3,5, dtype= 'int', k= -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [ ]:
zeros
ones
linespace
arange
eye

## 6. identity()   It is always 2x2 or 3x3 

In [27]:
array = np.identity(5, dtype='int')
array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
array = np.identity(3, dtype='int')
array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
array = np.identity(3,5, dtype='int')
array

TypeError: identity() got multiple values for argument 'dtype'

## 7. random()

In [ ]:
There are multiple function inside random function.
rand()
random()
randint()
randn()
ranf()

### 7.1 random.rand()

In [ ]:
It will always generate the random nos. from range 0 to 1.

In [30]:
arr1 = np.random.rand(5)
arr1

array([0.15254856, 0.53465365, 0.25309518, 0.65810373, 0.22869877])

In [31]:
np.random.rand(4)

array([0.03926274, 0.93156667, 0.34333088, 0.12908101])

In [32]:
np.random.rand(5)

array([0.3653875 , 0.29956306, 0.07450932, 0.32535253, 0.67991216])

In [33]:
arry1 = np.random.rand(50)
arry1

array([0.02074776, 0.39168662, 0.60258375, 0.0718478 , 0.80173647,
       0.4672457 , 0.1172067 , 0.20572794, 0.62674405, 0.68363126,
       0.91478679, 0.36109292, 0.69456937, 0.91815501, 0.08501021,
       0.13628429, 0.16753321, 0.21047505, 0.5339455 , 0.10280011,
       0.204881  , 0.63338894, 0.83745424, 0.47482913, 0.61781291,
       0.84848411, 0.91210397, 0.24549766, 0.41688713, 0.44812981,
       0.07022224, 0.61179372, 0.0681233 , 0.86751057, 0.32694613,
       0.24287001, 0.78430589, 0.32045018, 0.13171674, 0.55984572,
       0.00549694, 0.1413676 , 0.1980688 , 0.23732089, 0.25116137,
       0.6866665 , 0.96077513, 0.50952137, 0.45942004, 0.09433012])

In [34]:
np.random.rand(10)

array([0.30492248, 0.81240191, 0.99338474, 0.37034651, 0.02124486,
       0.60418464, 0.8676063 , 0.6303704 , 0.52835622, 0.95070576])

In [36]:
np.random.rand(2,4)

array([[0.55716499, 0.6973957 , 0.87780846, 0.38018555],
       [0.94693789, 0.86858937, 0.7108719 , 0.25250385]])

In [35]:
np.random.rand(2,5)

array([[0.22215958, 0.2434898 , 0.44389174, 0.56655319, 0.44773952],
       [0.0033366 , 0.04587274, 0.47024597, 0.4119096 , 0.32384631]])

In [37]:
np.random.rand(5,5)

array([[0.71289779, 0.3483874 , 0.86959149, 0.55347318, 0.21645324],
       [0.5097584 , 0.26478863, 0.07136851, 0.35557415, 0.44080871],
       [0.0820774 , 0.55821211, 0.28529325, 0.69777011, 0.50552868],
       [0.79770919, 0.28778369, 0.19205106, 0.49024976, 0.22367183],
       [0.73517451, 0.60621796, 0.53449294, 0.91361243, 0.02250994]])

## 7.2 random.random()        

In [ ]:
It will always generate the random nos. from range 0 to 1.

In [38]:
np.random.random(40)

array([0.99570386, 0.85688787, 0.79094974, 0.05391016, 0.33344973,
       0.24133136, 0.10286379, 0.51520917, 0.21079627, 0.62374873,
       0.38989866, 0.07261029, 0.26027373, 0.92426658, 0.23749411,
       0.61298258, 0.71539167, 0.1788514 , 0.80294838, 0.43158284,
       0.2037258 , 0.86412118, 0.56488774, 0.77008936, 0.55878961,
       0.41349158, 0.6183683 , 0.72269029, 0.39867574, 0.53389717,
       0.30985633, 0.91852388, 0.1006398 , 0.08946597, 0.27600495,
       0.10653555, 0.81616089, 0.38957236, 0.62146254, 0.17887075])

In [39]:
np.random.random(2,2)

TypeError: random() takes at most 1 positional argument (2 given)

In [40]:
np.random.random((2,2))

array([[0.99278253, 0.67067492],
       [0.62279319, 0.57787092]])

### 7.3 random.randint()    it gives us integer numbers 

In [41]:
np.random.randint(1,20)  # by default it is giving a only one random number

11

In [42]:
np.random.randint(1,20,10)

array([12,  9,  9,  6,  9,  2,  6,  8, 14, 17])

In [43]:
np.random.randint(1,20, size=20, dtype ='float')

TypeError: Unsupported dtype dtype('float64') for randint

In [44]:
np.random.randint(1,20, size=20, dtype ='int')

array([15, 16, 12, 11, 13,  4, 10,  3,  8, 11,  8, 19, 18,  8, 16, 16, 14,
       10, 13,  3])

In [45]:
np.random.randint(1,20, size=20)

array([14, 19, 14,  3, 13, 19, 13,  1,  9,  5,  6,  8, 12,  6,  8, 10,  6,
        3, 17, 13])

### 7.4 random.randn()

In [ ]:
It will retuen the normally distributed numbers around (0,0) co-ordinates.

In [ ]:
-3,-2,-,1,0,1,2,3

In [46]:
np.random.randn(2) # -2,-1,0,1,2

array([-1.71280604,  1.18988003])

In [47]:
np.random.randn(2,2)

array([[-1.03120093,  0.28313948],
       [-1.82416807,  1.70320736]])

In [48]:
np.random.randn(2,5)

array([[-2.4154469 ,  1.5172557 , -0.44164767,  0.31964582, -1.05766982],
       [-2.10269645,  1.44043202, -1.1193279 , -0.39851265,  1.45487633]])

### 5. random.ranf()    range(0-1)

In [49]:
np.random.ranf(2)

array([0.61325525, 0.67756609])

In [50]:
np.random.ranf(5)

array([0.41853508, 0.64595513, 0.62773425, 0.26423911, 0.68251091])

In [51]:
np.random.ranf((5,2))

array([[0.78056919, 0.65122836],
       [0.12753455, 0.35453224],
       [0.51169648, 0.21700184],
       [0.49050391, 0.09485886],
       [0.44129776, 0.24207972]])

In [52]:
np.random.ranf(5)

array([0.41631355, 0.27208697, 0.00833891, 0.41984279, 0.91466958])

In [ ]:
1) zeros()   it will create a zeros array
2) ones()   it will craete a ones array
3) arange()  it gives us a range of specific number  np.arange(start_index,end_index,step_size)
4) linspace()  it gives equally distributed numbers with the specific range 

np.linspace(start_index,end_index,num = int ,retstep = True)
num = how many numbers we want to dispaly with equal spacing

5) eye()  it gives a matrix with all digonals are one

6) identity()  it gives us identity matrics 
7) random
a) rand()      (0-1)
b) random()    (0-1)
c) randint()    random int
d) ranf()       (0-1)
e) randn()       normally distributed numbers

In [ ]:
import numpy as np

## sort()

np.sort()

In [53]:
array = np.random.randint(1,20, 10)
array

array([18,  8, 14,  2, 14, 15, 19, 11,  2,  2])

In [54]:
np.sort(array) # ascending 

array([ 2,  2,  2,  8, 11, 14, 14, 15, 18, 19])

In [55]:
str1 = "python"
str1[::-1]

'nohtyp'

In [56]:
np.sort(array)[::-1]   # desending order

array([19, 18, 15, 14, 14, 11,  8,  2,  2,  2])

## insert

In [ ]:
It insert an element inside array at a specific position.
# np.insert(array, position, element)

In [57]:
arr =  np.array([1,4,6,8])
arr 

array([1, 4, 6, 8])

In [58]:
np.insert(arr,2,30)

array([ 1,  4, 30,  6,  8])

In [59]:
arr

array([1, 4, 6, 8])

In [60]:
arra1= np.insert(arr, 1, 20)
arra1

array([ 1, 20,  4,  6,  8])

In [61]:
arr2 = np.array([1,3,5])
arr2

array([1, 3, 5])

In [62]:
arr

array([1, 4, 6, 8])

In [63]:
np.insert(arr, 1, arr2) # 1,1,3,5,4,6,8

array([1, 1, 3, 5, 4, 6, 8])

In [64]:
arr1 = np.array([1,2,3])
arra2 = np.array([4,5,6])
np.insert(arr1,3,arra2)  # 1,2,3,4,5,6

array([1, 2, 3, 4, 5, 6])

In [65]:
arr3 = arr1+arra2  #(1+4=5),(2+5=7)(3+6=9)
arr3

array([5, 7, 9])

In [66]:
str1 = "python"
str2 = "data"
str3 = str1 + " " +str2
str3

'python data'

## append

In [67]:
arr

array([1, 4, 6, 8])

In [68]:
arr2

array([1, 3, 5])

In [69]:
arr

array([1, 4, 6, 8])

In [70]:
np.append(arr, 10)

array([ 1,  4,  6,  8, 10])

In [71]:
np.append(arr, arr2)

array([1, 4, 6, 8, 1, 3, 5])

In [72]:
np.append(arr, (10,20))

array([ 1,  4,  6,  8, 10, 20])

In [73]:
arr3 = np.array([[1,2],[3,4]])
arr3,arr3.ndim

(array([[1, 2],
        [3, 4]]),
 2)

In [74]:
arr4 = np.array([[5,6]])
arr4,arr4.ndim

(array([[5, 6]]), 2)

In [75]:
arr5 = np.append(arr3,arr4) 
arr5,arr5.ndim

(array([1, 2, 3, 4, 5, 6]), 1)

In [77]:
arr3

array([[1, 2],
       [3, 4]])

In [79]:
arr4

array([[5, 6]])

In [76]:
np.append(arr3,arr4, axis=0)    # axis = 0 rows  

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
arr3

array([[1, 2],
       [3, 4]])

In [80]:
arr5 = np.array([[8,7],[3,4]])
arr5

array([[8, 7],
       [3, 4]])

In [82]:
np.append(arr3,arr5, axis=1)       # column

array([[1, 2, 8, 7],
       [3, 4, 3, 4]])

In [84]:
arr4

array([[5, 6]])

In [83]:
np.append(arr3,arr4,axis =1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [85]:
np.append(arr3,arr5, axis=0)

array([[1, 2],
       [3, 4],
       [8, 7],
       [3, 4]])

In [86]:
arr5 =  np.array([[7],[8]])
arr5

array([[7],
       [8]])

In [87]:
arr3

array([[1, 2],
       [3, 4]])

In [88]:
np.append(arr3,arr5, axis=1)

array([[1, 2, 7],
       [3, 4, 8]])

In [89]:
np.append(arr3,arr5, axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

## concatenate()

concatenate the arrays along with the axis

In [ ]:
array1 = np.array([1,2,3])
array2 = np.concatenate([array1, [10]])
array2

In [ ]:
array1 = np.array([1,2,3])
array2 = np.concatenate([array1, [[10]]])
array2

In [ ]:
array1 = np.array([[1,2,3]])
array2 = np.concatenate([array1, [[10]]])
array2

In [ ]:
array1 = np.array([[1,2,3]])
array2 = np.concatenate([array1, [[10,2,3]]])
array2

In [ ]:
array1 = np.array([[1]])
array2 = np.concatenate([array1, [[10]]])
array2

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([5,6,7])
array3 = np.array([9,10,11])
np.concatenate([array1,array2, array3])

In [ ]:
np.concatenate([array1,array3, array2])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
np.concatenate([arr1,arr2,arr3])

In [ ]:
np.concatenate([arr1,arr3,arr2])

In [ ]:
arr3

In [ ]:
arr4

In [ ]:
np.append(arr3,arr4)

In [ ]:
np.concatenate([arr3,arr4])

In [ ]:
arr3

In [ ]:
arr5

In [ ]:
np.concatenate([arr3,arr5], axis=1)

In [ ]:
axis = 0 >> it is about concatinating row wise
axis = 1 >> is about concatinating column wise

# Iteration of array 

In [ ]:
for i in arr:
    print(i)

In [ ]:
list1 = [1,2,3,4]
for i in list1:
    print(i

In [ ]:
for i,ele in enumerate(list1):
    print("index",i,"element",ele)

In [ ]:
for i , val in np.ndenumerate(arr):
    print("index",i,"element", val)

In [ ]:
arr3

In [ ]:
for i , val in np.ndenumerate(arr3):
    print(i, val)

In [ ]:
for i in np.nditer(arr):
    print(i)

In [ ]:
for i in np.nditer(arr3):
    print(i)
    

## Ceil

In [ ]:
-2.1 >> -2
-2.5 >> -2
2.6 >> 3
it returns round figure of closest maximum value.

In [ ]:
np.ceil(2.1)    # 

In [ ]:
np.ceil(2.5)   # 3

In [ ]:
np.ceil(-2.1)    # 

In [ ]:
np.ceil(3.4)  

In [ ]:
np.ceil(-2.8)

## floor

In [ ]:
it reduces the number to its closest minimum whole number.

In [ ]:
np.floor(2.6)  #

In [ ]:
np.floor(2.9)  #

In [ ]:
np.floor(-2.1)  #

## around()

In [ ]:
np.around(2.6)

In [ ]:
np.around(2.1)

In [ ]:
np.around(2.5)

In [ ]:
np.around([4.2,3.8,1.1])  # 4,4,1


## copy

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
arr2 = arr.copy()
arr2

In [ ]:
arr3 = np.array([[1,2],[3,4]])
arr3

In [ ]:
arr4 = arr3.copy() # it works like deep copy
arr4

## where

In [ ]:
np.where

In [ ]:
arr = np.array([4,2,3,7])
np.where(arr==2)

In [ ]:
arr = np.array([4,2,3,7,4,5,4])
np.where(arr==4)

In [ ]:
arr = np.array([4,2,3,7,4,5,4])
np.where(arr==4, 20 ,arr)

## size

In [ ]:
arr

In [ ]:
np.size(arr)

In [ ]:
arr2 = np.array([4,5,2,11,7,8,1])
arr2
np.size(arr2)
len(arr2)

## argmax it gives indexing of the maximum number 

In [ ]:
arr2

In [ ]:
np.argmax(arr2)

In [ ]:
arr3 = np.array([90,5,7,8])
np.argmax(arr3)

## argmin   

In [ ]:
arr2

In [ ]:
np.argmin(arr2)

## argsort

In [ ]:
arr2

In [ ]:
1,2,4,5,7,8,11
6,2,0,1,4,5,3

In [ ]:
np.argsort(arr2) # 1=6,2=2, 4=0, 5=1,7=4,8=5,11=3

In [ ]:
np.sort(arr2)

In [ ]:
np.sum(arr2)

In [ ]:
np.mean(arr2)                    #avg

In [ ]:
np.median(arr2)     #1,2,3,4,5,

In [ ]:
np.std(arr2) # standard deviation = summation(a -a.mean())**2

In [ ]:
np.square(arr2)

In [ ]:
np.power(arr2, 2)

In [ ]:
np.power(arr2, 4)

In [ ]:
arr2

In [ ]:
arr2 + 5

In [ ]:
arr2 -1

In [ ]:
arr2*2

In [ ]:
arr2/2

In [ ]:
arr2%2     # reminder

In [ ]:
arr

In [ ]:
arr2

In [ ]:
arr + arr2

In [ ]:
arr3 = np.array([1,7,8,6])
arr3

In [ ]:
arr3 + arr2 # shape of array should be same.

In [ ]:
np.add(arr,arr2)

In [ ]:
np.multiply(arr, arr2)

In [ ]:
np.subtract(arr, arr2)

In [ ]:
np.multiply(arr, arr2)

In [ ]:
np.divide(arr,arr2)